version: "3.7"

services:
  app:
    build:
      args:
        user: robusta
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: fleet-management-system
    container_name: fleet-management-system-app
    restart: unless-stopped
    working_dir: /var/www/
    env_file: .env
    volumes:
      - ./:/var/www
    networks:
      - fleet-management-system

  db:
    image: mysql:5.7
    container_name: fleet-management-system-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - fleet-management-system

  nginx:
    image: nginx:1.17-alpine
    container_name: fleet-management-system-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - fleet-management-system

volumes:
  dbdata:
    driver: local

networks:
  fleet-management-system:
    driver: bridge